use anyhow::Result;
use crate::context::Dependency;
use crate::intelligence::Insight;
use std::path::Path;
use tokio::fs;
use chrono::Local;

pub async fn generate_report(output_path: &Path, deps: &[Dependency], insights: &[Insight]) -> Result<()> {
    let mut content = String::new();

    // YAML Frontmatter
    content.push_str("---\n");
    content.push_str("title: \"Living Research Context\"\n");
    content.push_str("type: RESEARCH\n");
    content.push_str("agent: context-research-agent\n");
    content.push_str(&format!("updated: {}\n", Local::now().format("%Y-%m-%d")));
    content.push_str("---\n\n");

    content.push_str("# 🧠 Living Research Context\n\n");
    content.push_str("> **Auto-generated by Context Research Agent.**\n");
    content.push_str("> This document provides context-aware intelligence for the current project stack.\n\n");

    // 1. Current Stack
    content.push_str("## 📦 Current Stack\n\n");
    content.push_str("| Dependency | Version | Ecosystem |\n");
    content.push_str("|------------|---------|-----------|\n");
    for dep in deps {
        content.push_str(&format!("| **{}** | `{}` | {:?} |\n", dep.name, dep.version, dep.ecosystem));
    }
    content.push_str("\n");

    // 2. Intelligent Insights
    content.push_str("## 🧠 Intelligent Patterns & Anomalies\n\n");
    content.push_str("> Analyzed by **GitHub Models (GPT-4o-mini)** - Free tier via `gh models run`.\n\n");

    if insights.is_empty() {
        content.push_str("*No specific anomalies detected for the current stack versions.*\n");
    } else {
        for insight in insights {
            content.push_str(&format!("### {} ({})\n\n", insight.dependency_name, insight.version));
            content.push_str(&insight.analysis);
            content.push_str("\n\n---\n\n");
        }
    }

    // Ensure directory exists
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).await?;
    }

    fs::write(output_path, content).await?;

    Ok(())
}
